#!/bin/sh
NAME="busybox"
install_package(){
  (
    cd $1/bin
    curl https://www.busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox -o busybox
    chmod 777 ./busybox
  )
}
remove_package(){
  rm -rf $1/bin/busybox
}
