#!/bin/sh
NAME="FHS"
install_package(){
  (
    cd $1/
    mkdir -pv ./{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt,proc,sys}
    mkdir -pv ./{media/{floppy,cdrom},srv,var}
    install -dv -m 0750 ./root
    install -dv -m 1777 ./tmp ./var/tmp
    mkdir -pv ./usr/{,local/}{include,lib,src}
    mkdir -pv ./usr/{,local/}share/{color,dict,doc,info,locale,man}
    mkdir -v  ./usr/{,local/}share/{misc,terminfo,zoneinfo}
    mkdir -v  ./usr/libexec
    mkdir -pv ./usr/{,local/}share/man/man{1..8}

    case $(uname -m) in
     x86_64) mkdir -v /lib64 ;;
    esac

    mkdir -v ./var/{log,mail,spool,db}
    ln -sv ./run /var/run
    ln -sv ./run/lock /var/lock
    mkdir -pv ./var/{opt,cache,lib/{color,misc,locate},local}
    ln -sf bin sbin
    ln -sf ../bin usr/sbin
    ln -sf ../bin usr/bin
    ln -sf ../../bin usr/local/bin
    ln -sf ../../bin usr/local/sbin
  )
}
remove_package(){
  rm -rf $1/*
}
