#!/bin/sh
NAME="kernel"
install_package(){
  curl https://slackware.uk/slackware/slackware64-current/slackware64/a/kernel-huge-6.1.22-x86_64-1.txz -o /tmp/kh.tar.xz
  rm -rf /tmp/flow/kh
  mkdir -p /tmp/flow/kh
  tar -xf /tmp/kh.tar.xz -C /tmp/flow/kh/
  mkdir -p $1/boot
  cp /tmp/flow/kh/boot/* $1/boot/
  (
    cd $1/
    sh /tmp/flow/kh/install/doinst.sh
  )
  
}
remove_package(){
  rm -rf $1/boot/*
}
